### ISSUE TITLE
Lower the number of buffer views

### ISSUE THREAD

**Issue by bartgol** [E3SM-Project/HOMMEXX#187]
Perhaps the best way to do this is to give them "generic" names (e.g., scalar_3d_buf_1, tracers_buf_1, tracers_buf_2, vector_3d_buf_1,...), and then when one is needed, alias it with possibly a better name, like

`
auto& pressure = m_elements.buffers.scalar_3d_buf_2;
`

**Comment by ambrad** [comment]
Closing; this approach was incorporated into all pieces by now.
