### ISSUE TITLE
No use of singletons

### ISSUE THREAD

**Issue by mfdeakin-sandia** [E3SM-Project/HOMMEXX#210]
There's very rarely an actual need for singletons (and worse, they are global state, preventing things from being significantly better than a monolithic procedural approach) - in this case we used them to avoid having to pass pointers up to Fortran and back down to C++ when we needed them. Now that we are end to end, this isn't really needed, and will be enabled when we've written the actual timestep loop in C++.

**Comment by ambrad** [comment]
Context reduces to 1 singleton in standalone, and Michael is working on 0 singletons in CAM.
