### ISSUE TITLE
Support and test diagnostics

### ISSUE THREAD

**Issue by ambrad** [E3SM-Project/HOMMEXX#283]
It's not clear we want to rewrite all of prim_printstate and code on which it depends, such as repro_sum. We might find it simplest to convert prim_energy_halftimes and prim_diag_scalars, or we might prefer to call the existing Fortran routines. In any case, once this has been done, we also want to test diagnostic output, which is separate from netcdf output.

- [ ] Call or convert prim_diag_scalars.
- [ ] Call or convert prim_energy_halftimes.
- [ ] Undo USE_KOKKOS_KERNELS guards.
- [ ] Visually verify output, and merge at this point.
- [ ] In a separate PR, add a test for the diagnostic output. String cmp should be enough since we do BFB testing anyway.

**Comment by mfdeakin-sandia** [comment]
I assume this can be closed since we have diagnostics in HOMMEXX? If not, please reopen
