### ISSUE TITLE
Pascal tests are failing since ~6/14

### ISSUE THREAD

**Issue by ambrad** [E3SM-Project/HOMMEXX#334]
GPU tests are failing because of
```
src/share/cxx/RemapFunctor.hpp(458): warning: calling a __host__ function("__builtin_isnan") from a __host__ __device__ function("Kokkos::parallel_reduce<int,  ::, int> ") is not allowed
```
`--expt-relaxed-constexpr` is not sufficient. Cuda provides its own
isnan. We can abstract Cuda's isnan vs `std::isnan` in ExecSpaceDefs.

**Comment by bartgol** [comment]
Sorry, this was my fault. Should have known better than using std:: stuff...
